### PR TITLE
Format table

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by peterdesmet** [comment]
I can also branch from `develop` if you want.

**Comment by ThierryO** [comment]
Yes. Pull request should go to the develop branch. That's why I commented and closed #5

**Comment by ThierryO** [comment]
The current master branch won't pass the CI tests because the repository has been moved.

**Comment by peterdesmet** [comment]
This pull request goes to the `develop` branch, but was branched from the `master` branch (which is why there are conflicts). Do you want me to branch from `develop` instead?

**Comment by ThierryO** [comment]
Sorry. I misread the pull request.

New feature branches should branch of from `develop` and send pull requests back to `develop`. Only hotfixes go directly to `master`.

**Pull request closed without merging**
